# Generated by Django 6.1 on 2026-08-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name of the medicine e.g. Augmentin 625 Duo', max_length=255)),
                ('generic_name', models.CharField(blank=True, help_text='Salt composition e.g. Amoxicillin & Clavulanate', max_length=255, null=True)),
                ('dosage_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup / Suspension'), ('Injection', 'Injection'), ('Ointment', 'Ointment / Cream / Gel'), ('Drops', 'Eye / Ear / Nasal Drops'), ('Inhaler', 'Inhaler / Respules'), ('Powder', 'Powder / Granules'), ('Device', 'Medical Device / Kit'), ('Other', 'Other Consumable')], default='Tablet', max_length=50)),
                ('strength', models.CharField(blank=True, help_text='e.g. 625mg, 500mg, 100ml', max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='e.g. Sun Pharma, Cipla, GSK', max_length=150, null=True)),
                ('hsn_code', models.CharField(default='3004', help_text='HSN Code for GST', max_length=50)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rack_location', models.CharField(blank=True, help_text='e.g. Rack A-3, Shelf 2, Fridge', max_length=100, null=True)),
                ('min_stock_alert', models.IntegerField(default=10, help_text='Low stock alert threshold (in packs)')),
                ('requires_prescription', models.BooleanField(default=False, help_text='Schedule H / H1 Rx requirement')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='GST percentage (e.g. 0, 5, 12, 18)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('expiry_date', models.DateField(db_index=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase/Cost price per full pack', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price per full pack', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per full pack', max_digits=10)),
                ('pack_size', models.PositiveIntegerField(default=10, help_text='Units per pack (e.g. 10 tablets/strip, 1 bottle)')),
                ('pack_quantity', models.IntegerField(default=0, help_text='Full pack quantity in stock')),
                ('loose_quantity', models.IntegerField(default=0, help_text='Loose units in stock (0 to pack_size-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Stock Purchase / Inward'), ('SALE', 'Sale Billing'), ('RETURN', 'Customer Return'), ('VENDOR_RETURN', 'Returned to Vendor'), ('ADJUSTMENT', 'Inventory Adjustment'), ('EXPIRED_DISCARD', 'Expired Stock Quarantine/Discard')], max_length=20)),
                ('quantity_packs', models.IntegerField(default=0)),
                ('quantity_loose', models.IntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, help_text='Invoice #, PO # or Reason', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
