# Generated by Django 4.2.28 on 2026-08-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, db_index=True, help_text='Salt composition e.g. Amoxicillin & Clavulanate', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, help_text='Brand name of the medicine e.g. Augmentin 625 Duo', max_length=255),
        ),
    ]
