# Generated by Django 6.1 on 2026-08-23 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(blank=True, default='General Physician', max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Medical Council Reg No', max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Top Medical Pharmacy', max_length=200)),
                ('tagline', models.CharField(default='Quality Care & Trusted Medications', max_length=255)),
                ('address', models.TextField(default='Shop 4, City Care Complex, Main Health Road')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='billing@topmedical.com', max_length=254)),
                ('gstin', models.CharField(default='29ABCDE1234F1Z5', max_length=50)),
                ('dl_number_20b', models.CharField(default='KA-B1-20B-123456', help_text='Drug License 20B (Allopathic)', max_length=100)),
                ('dl_number_21b', models.CharField(default='KA-B1-21B-123457', help_text='Drug License 21B', max_length=100)),
                ('fssai_number', models.CharField(blank=True, default='11223344556677', max_length=100, null=True)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('invoice_footer_note', models.TextField(default="1. Goods once sold will be taken back only within 7 days with original bill.\n2. Please check expiry dates and doctor's prescription before consuming.")),
                ('upi_id', models.CharField(default='topmedical@upi', help_text='UPI VPA ID for dynamic QR payments', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Unpaid dues', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('prescription_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('CARD', 'Debit / Credit Card'), ('CREDIT', 'Due / Credit Account'), ('MIXED', 'Split Payment')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('DUE', 'Unpaid / Due'), ('CANCELLED', 'Cancelled / Void'), ('REFUNDED', 'Returned & Refunded')], default='PAID', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total GST (CGST + SGST)', max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('change_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.customer')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('hsn_code', models.CharField(default='3004', max_length=50)),
                ('is_loose', models.BooleanField(default=False, help_text='True if sold as single units / tablets')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('pack_size', models.PositiveIntegerField(default=10)),
                ('unit_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.batch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.medicine')),
            ],
        ),
    ]
