# Generated by Django 6.1 on 2026-08-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('charge_code', models.CharField(db_index=True, help_text='Unique charge code e.g. SC-101', max_length=50, unique=True)),
                ('role', models.CharField(default='Pharmacist / Cashier', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['charge_code'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff_code',
            field=models.CharField(blank=True, db_index=True, help_text='Staff charge code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff_name',
            field=models.CharField(blank=True, default='Staff 1', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='staff_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='staff_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, default='Walk-in Customer', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.staffmember'),
        ),
    ]
