# Generated by Django 4.2.28 on 2026-08-25 08:11

from django.db import migrations, models
from decimal import Decimal

def backfill_invoice_payments(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    for inv in Invoice.objects.all():
        paid = inv.amount_paid or inv.grand_total or Decimal('0.00')
        if inv.payment_method == 'CASH':
            inv.cash_amount = paid
            inv.upi_amount = Decimal('0.00')
            inv.card_amount = Decimal('0.00')
        elif inv.payment_method in ['UPI', 'GPAY']:
            inv.upi_amount = paid
            inv.cash_amount = Decimal('0.00')
            inv.card_amount = Decimal('0.00')
        elif inv.payment_method == 'CARD':
            inv.card_amount = paid
            inv.cash_amount = Decimal('0.00')
            inv.upi_amount = Decimal('0.00')
        inv.save()

def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_staffmember_invoice_staff_code_invoice_staff_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Card received for this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cash received for this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='upi_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total UPI / GPay received for this invoice', max_digits=12),
        ),
        migrations.RunPython(backfill_invoice_payments, reverse_backfill),
    ]

