# Generated by Django 6.1 on 2026-09-16 08:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_card_amount_invoice_cash_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='address',
            field=models.TextField(default='3-79/4, R.B.COMPLEX, GROUND FLOOR, UNIVERSITY ROAD, DERALAKATTE, ULLAL TALUK, DERALAKATTE, MANGALORE 575018'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='dl_number_20b',
            field=models.CharField(default='KA-MN1-300667', help_text='Drug License (DL No.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='dl_number_21b',
            field=models.CharField(blank=True, default='KA-MN1-300667', help_text='Drug License 21B', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='gstin',
            field=models.CharField(default='29AJPPU6288G1Z7', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='phone',
            field=models.CharField(default='9148240793', max_length=50),
        ),
        migrations.CreateModel(
            name='DailyFinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('daily_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gross sales invoiced/recorded on this day', max_digits=14)),
                ('cash_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Cash payments received', max_digits=14)),
                ('upi_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total UPI / QR digital payments received', max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money earned: Cash + UPI', max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money paid out', max_digits=14)),
                ('supplier_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock & wholesaler payouts', max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Day-to-day shop expenses: rent, electricity, courier, tea, staff, etc.', max_digits=14)),
                ('other_outflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other miscellaneous expenses or drawings', max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Firm starting balance at opening of day', max_digits=14)),
                ('net_day_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net day change: total_earned - total_paid', max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Closing balance in the firm: opening_balance + total_earned - total_paid', max_digits=14)),
                ('payment_details', models.JSONField(blank=True, default=list, help_text='Itemized list of payments and expenses')),
                ('notes', models.TextField(blank=True, help_text='Daily financial notes / explanations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_finance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
