# Generated by Django 6.1 on 2026-09-16 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_pharmacyprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfinancerecord',
            name='staff_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total staff expenses mapped with charge codes (salary, allowance, tea)', max_digits=14),
        ),
        migrations.AddField(
            model_name='dailyfinancerecord',
            name='vehicle_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total delivery vehicle & fuel expenses', max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyfinancerecord',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Day-to-day shop operational expenses: rent, electricity, maintenance, etc.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailyfinancerecord',
            name='payment_details',
            field=models.JSONField(blank=True, default=list, help_text='Itemized list of payments (vendors, staff with charge codes, vehicle, shop)'),
        ),
        migrations.AlterField(
            model_name='dailyfinancerecord',
            name='supplier_payments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total paid to medicine vendors/wholesalers', max_digits=14),
        ),
    ]
