# Generated by Django 4.2.28 on 2026-09-16 10:11

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_medicine_generic_name_alter_medicine_name'),
        ('billing', '0005_dailyfinancerecord_staff_expenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(db_index=True, max_length=200)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_number', models.CharField(db_index=True, help_text='Supplier invoice/bill number', max_length=100)),
                ('bill_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('credit_days', models.PositiveIntegerField(default=21, help_text='Agreed credit period in days')),
                ('due_date', models.DateField(db_index=True, help_text='Payment due date (bill_date + credit_days)')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total bill amount including GST', max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid against this bill', max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining pending balance', max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled / Disputed')], db_index=True, default='PENDING', max_length=20)),
                ('payment_history', models.JSONField(blank=True, default=list, help_text='List of payment logs: date, amount, mode, ref, notes, logged_in_daily_finance')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='inventory.supplier')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'unique_together': {('supplier_name', 'bill_number')},
            },
        ),
    ]
